version: '3.7'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root!
      POSTGRES_DB: galaxy-db

    ports:
      - "5432:5432"
    volumes:
      - galaxy-db:/var/lib/postgresql/data 
    networks:
      - galaxy-net    

networks: 
  galaxy-net:
    driver: bridge

volumes:
  galaxy-db:
    driver: local
